### ISSUE TITLE
Error after updating my enet controller to 2.3.1

### ISSUE THREAD

**Issue by bartdesign** [lawrencebensaid/homebridge-enet#1]
Hi, I was using the plugin without problems. I just updated and now the plugin causes a crash after starting and it makes homebridge restart. It does not show any accessories. I've tried to debug it, but it stops in the setupnow() part. Further than that i couldn't really understand anymore ;-) 

TypeError: Cannot read properties of undefined (reading 'message')
    at C:\Users\Beheerder\AppData\Roaming\npm\node_modules\homebridge-enet\src\dynamic-platform.ts:125:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[9-11-2021 20:42:42] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal:

full message: 
[9-11-2021 20:47:36] [HB Supervisor] Starting Homebridge with extra flags: -I
[9-11-2021 20:47:36] [HB Supervisor] Started Homebridge v1.3.5 with PID: 6800
Initializing HAP-NodeJS v0.9.6...
[9-11-2021 20:47:37] Loaded config.json with 0 accessories and 2 platforms.
[9-11-2021 20:47:37] ---
[9-11-2021 20:47:37] Loaded plugin: homebridge-config-ui-x@4.41.2
[9-11-2021 20:47:37] Registering platform 'homebridge-config-ui-x.config'
[9-11-2021 20:47:37] ---
[9-11-2021 20:47:38] Loaded plugin: homebridge-enet@1.0.1
[9-11-2021 20:47:38] Registering platform 'homebridge-enet.eNetPlatform'
[9-11-2021 20:47:38] ---
[9-11-2021 20:47:38] Loading 2 platforms...
[9-11-2021 20:47:38] [Config] Initializing config platform...
[9-11-2021 20:47:38] [Config] Running in Service Mode
[9-11-2021 20:47:38] [eNetPlatform] Initializing eNetPlatform platform...
[9-11-2021 20:47:38] [eNetPlatform] eNet start initializing!
Preparing Advertiser for 'Homebridge 8BB0 14C9' using bonjour-hap backend!
Setup Payload:
X-HM://0XXXXXXX
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ XXX-XX-XXX │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 8BB0 14C9' using bonjour-hap backend!
[9-11-2021 20:47:38] Homebridge v1.3.5 (Homebridge 8BB0) is running on port 51897.
Unauthorized
[9-11-2021 20:47:39] TypeError: Cannot read properties of undefined (reading 'message')
    at C:\Users\Beheerder\AppData\Roaming\npm\node_modules\homebridge-enet\src\dynamic-platform.ts:125:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[9-11-2021 20:47:39] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[9-11-2021 20:47:44] [HB Supervisor] Restarting Homebridge...

**Comment by markussemmelmann** [comment]
Hi, i´ve the same problem:

Unauthorized
[15/11/2021, 22:32:19] TypeError: Cannot read properties of undefined (reading 'message')
    at /usr/local/lib/node_modules/homebridge-enet/src/dynamic-platform.ts:107:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[15/11/2021, 22:32:19] Got SIGTERM, shutting down Homebridge...

I would be so great if your plugin would work!

**Comment by bartdesign** [comment]
I manged to fix this myself. It turns out there is an issue with the line; 16 of main.js of the enet-api module located in the `C:\Users\username\AppData\Roaming\npm\node_modules\homebridge-enet\node_modules\enet-api\src` folder of my system. 

I'm using windows, i changed line 16 from: 

> `const cpath = `${process.env.HOME}/.enet`;  `

to: 

> const cpath = `C:\\users\\username\\.enet`;

After that i can restart homebridge and everything works again ;-)

**Comment by Adversio** [comment]
Having the same issues but i,m using a mac as homebridge, tried everything with changing the path but i cannot get it to work.

**Comment by webdevsmarthome** [comment]
Same problem on using docker on Synology DiskStation. Tried also some path variations, no success. 
I would be really happy, somebody can help and solve the issue. Many thanks.

**Comment by huglester** [comment]
I had similar error, later somehow restarted the device, enabled "remote" access.
And it started working, kind of.

It started showing devices in logs, later Homebridge gets restarted:

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 7bcd9fa1-9244-4bfc-92a8-d873000006d2".

**Comment by shanse01** [comment]
Is this Plugin intended for use with the ENet-Server?
Upon installing this plugin I get the following error (docker on Sinology):
TypeError: enet_api_1.ENet is not a constructor
    at new ENetPlatform (/homebridge/node_modules/homebridge-enet/src/dynamic-platform.ts:60:19)
    at /homebridge/node_modules/homebridge/src/server.ts:473:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/homebridge/node_modules/homebridge/src/server.ts:400:27)
    at Server.start (/homebridge/node_modules/homebridge/src/server.ts:176:29)

**Comment by huglester** [comment]
Anyone here got it working please?

**Comment by Adversio** [comment]
Nope, i tried to contact lawrence but he does nog respond anymore. It is me something worth to get this up and running.


Met vriendelijke groet,

Mark Vork

tel +31 (297) 227622

e-mail ***@***.***
KvK 34243559

________________________________
Van: huglester ***@***.***>
Verzonden: Friday, December 30, 2022 7:54:10 PM
Aan: lawrencebensaid/homebridge-enet ***@***.***>
CC: Mark Vork ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)


Anyone here got it working please?

**Comment by huglester** [comment]
Well this tool is definately worth. Its the only and almost works. Just needs some tuning

**Comment by Adversio** [comment]
I hope Lawrence wants to pick it up again and make it running again. I already told him I'm willing to pay for it :)


Met vriendelijke groet,

Mark Vork

tel +31 (297) 227622

e-mail ***@***.***
KvK 34243559

________________________________
Van: huglester ***@***.***>
Verzonden: Saturday, December 31, 2022 10:17:07 AM
Aan: lawrencebensaid/homebridge-enet ***@***.***>
CC: Mark Vork ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)


Well this tool is definately worth. Its the only and almost works. Just needs some tuning

**Comment by webdevsmarthome** [comment]
Me too, I'm also willing to pay for this plug in. I would be really happy this would be working. :-)

**Comment by Adversio** [comment]
I’m curious how many people use the plug-in.


Met vriendelijke groet,

Mark Vork

tel +31 (297) 227622

e-mail ***@***.***
KvK 34243559

________________________________
Van: webdevsmarthome ***@***.***>
Verzonden: Saturday, December 31, 2022 10:34:45 AM
Aan: lawrencebensaid/homebridge-enet ***@***.***>
CC: Mark Vork ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)


Me too, I'm also willing to pay for this plug in. I would be really happy this would be working. :-)

**Comment by shanse01** [comment]
Good morning everybody!Actually I contacted Lawrence by e-mail and he responded just a few minutes later. He will come back to this early/mid January he said. If this works it will be a giant leap for my smart home 😀.So let us just wait a few more days.You all have a Happy New Year 2023 🥳!Mit freundlichem Gruß/Best regardsSven ***@***.*** 31.12.2022 um 10:41 schrieb Adversio ***@***.***>:﻿
I’m curious how many people use the plug-in.


Met vriendelijke groet,

Mark Vork

tel +31 (297) 227622

e-mail ***@***.***
KvK 34243559

________________________________
Van: webdevsmarthome ***@***.***>
Verzonden: Saturday, December 31, 2022 10:34:45 AM
Aan: lawrencebensaid/homebridge-enet ***@***.***>
CC: Mark Vork ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)


Me too, I'm also willing to pay for this plug in. I would be really happy this would be working. :-)

**Comment by huglester** [comment]
These are good news. Okay lets wait for him. I was fighting recompiling classes woth different typescript versions, and always get error or another

**Comment by huglester** [comment]
I wonder if this gateway has maybe some direct homekit integration?

https://www.manualslib.com/manual/1523359/Jung-Enet-Fm-Gate-Ip.html#manual

**Comment by Adversio** [comment]
Nope, there are also homebridge plugins for it, I think I have one laying around somewhere but cannot find. I was wondering also if the plug-in is any good. Officially its not supported anymore bij eNet. It works only with encryption disabled. I use to have one when the eNet server was in version 1 this gateway was used to connect your mobile device to your eNet system.


Met vriendelijke groet,

Mark Vork

tel +31 (297) 227622

e-mail ***@***.***
KvK 34243559

________________________________
Van: huglester ***@***.***>
Verzonden: Sunday, January 1, 2023 1:46:43 PM
Aan: lawrencebensaid/homebridge-enet ***@***.***>
CC: Mark Vork ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)


I wonder if this gateway has maybe some direct homekit integration?

https://www.manualslib.com/manual/1523359/Jung-Enet-Fm-Gate-Ip.html#manual<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.manualslib.com%2Fmanual%2F1523359%2FJung-Enet-Fm-Gate-Ip.html%23manual&data=05%7C01%7Cmark%40adversio.nl%7Cd8ee8bbe73724d65a80108daebf63cea%7C9cfe240effe94bd49807a85179139783%7C0%7C0%7C638081740056456807%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JIg%2FT6xEwAhFx%2FddO9D619D4S82NdyLucmfcTTTTV%2Bo%3D&reserved=0>

**Comment by huglester** [comment]
> Good morning everybody!Actually I contacted Lawrence by e-mail and he responded just a few minutes later. He will come back to this early/mid January he said. If this works it will be a giant leap for my smart home 😀.So let us just wait a few more days.You all have a Happy New Year 2023 🥳!Mit freundlichem Gruß/Best regardsSven ***@***.*** 31.12.2022 um 10:41 schrieb Adversio ***@***.***>:﻿ I’m curious how many people use the plug-in. Met vriendelijke groet, Mark Vork tel +31 (297) 227622 e-mail ***@***.*** KvK 34243559
> […](#)

Hey! Wanted to ask maybe we have update on this case? Is everything going as planned? :)

**Comment by huglester** [comment]
I tried to make some progress here 
https://github.com/lawrencebensaid/homebridge-enet/pull/3

but enet-api also needs updated version ( I made PR also)

There are still some notices, but it is already a progress. 
I see Devices now in logs when homebridge configured.

**Comment by markussemmelmann** [comment]
> Good morning everybody!Actually I contacted Lawrence by e-mail and he responded just a few minutes later. He will come back to this early/mid January he said. If this works it will be a giant leap for my smart home 😀.So let us just wait a few more days.You all have a Happy New Year 2023 🥳!Mit freundlichem Gruß/Best regardsSven ***@***.*** 31.12.2022 um 10:41 schrieb Adversio ***@***.***>:﻿ I’m curious how many people use the plug-in. Met vriendelijke groet, Mark Vork tel +31 (297) 227622 e-mail ***@***.*** KvK 34243559



Hi - i´m also very interested in the plug-in!

**Comment by huglester** [comment]
@shanse01 - hey maybe you have any updates?

**Comment by huglester** [comment]
@lawrencebensaid hey. Any idea when you will be able to check this?

**Comment by lawrencebensaid** [comment]
It's nice to see there is so much engagement with this plugin. Thank you all.
A new version (v1.2.0) has been released. This should solve most of the issues you experienced. @bartdesign could you please confirm if you still get the same error message?

**Comment by Adversio** [comment]
Can’t wait to get home and try it 😊 Thanks!

Met vriendelijke groet,

Mark Vork




From: Lawrence Bensaid ***@***.***>
Date: Monday, 23 January 2023 at 12:17
To: lawrencebensaid/homebridge-enet ***@***.***>
Cc: Mark Vork ***@***.***>, Comment ***@***.***>
Subject: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)

It's nice to see there is so much engagement with this plugin. Thank you all.
A new version (v1.2.0) has been released. This should solve most of the issues you experienced. @bartdesign<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbartdesign&data=05%7C01%7Cmark%40adversio.nl%7Cb49a8ab62979422eeb5f08dafd3368ae%7C9cfe240effe94bd49807a85179139783%7C0%7C0%7C638100694500688316%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EjVi9SzxATdG1%2FVPUtpFiTlOm1GdMVIvnfxFtlw84ro%3D&reserved=0> could you please confirm if you still get the same error message?

**Comment by huglester** [comment]
@Adversio let me know how is it going. I am getting this error now:
https://github.com/lawrencebensaid/homebridge-enet/issues/4

**Comment by Adversio** [comment]
I’m getting the same error

[23/01/2023, 17:19:47] TypeError: Cannot read properties of undefined (reading 'message')
    at /usr/local/lib/node_modules/homebridge-enet/src/dynamic-platform.ts:105:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Anyone got any luck on the new update?

Regards,

Mark



Van: huglester ***@***.***>
Datum: maandag, 23 januari 2023 om 16:19
Aan: lawrencebensaid/homebridge-enet ***@***.***>
CC: Mark Vork ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)

@Adversio<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdversio&data=05%7C01%7Cmark%40adversio.nl%7C40792de64506413546bc08dafd552e33%7C9cfe240effe94bd49807a85179139783%7C0%7C0%7C638100839535912851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RQMSlo%2FDDjSVgeY24BUiEhQgFA15Gx8wNDgkJG%2FYno0%3D&reserved=0> let me know how is it going. I am getting this error now:
#4<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flawrencebensaid%2Fhomebridge-enet%2Fissues%2F4&data=05%7C01%7Cmark%40adversio.nl%7C40792de64506413546bc08dafd552e33%7C9cfe240effe94bd49807a85179139783%7C0%7C0%7C638100839536069055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FlVy1p9kvZqjIwypPXupCv%2BHSO%2F8%2BRZquKYftKIHrwc%3D&reserved=0>

**Comment by Adversio** [comment]
Hi!,

I installed Home-Bridge on a mac to see if that runs and it seems to work, there are 32 connections loaded in Homebridge and they show up in homekit. Only thing is that nothing happens when I try to switch.. And whats even worse, my eNet server crashes. I hope I can get it up and running again…

Met vriendelijke groet,

Mark Vork



Van: huglester ***@***.***>
Datum: maandag, 23 januari 2023 om 16:19
Aan: lawrencebensaid/homebridge-enet ***@***.***>
CC: Mark Vork ***@***.***>, Mention ***@***.***>
Onderwerp: Re: [lawrencebensaid/homebridge-enet] Error after updating my enet controller to 2.3.1 (Issue #1)

@Adversio<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAdversio&data=05%7C01%7Cmark%40adversio.nl%7C40792de64506413546bc08dafd552e33%7C9cfe240effe94bd49807a85179139783%7C0%7C0%7C638100839535912851%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RQMSlo%2FDDjSVgeY24BUiEhQgFA15Gx8wNDgkJG%2FYno0%3D&reserved=0> let me know how is it going. I am getting this error now:
#4<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flawrencebensaid%2Fhomebridge-enet%2Fissues%2F4&data=05%7C01%7Cmark%40adversio.nl%7C40792de64506413546bc08dafd552e33%7C9cfe240effe94bd49807a85179139783%7C0%7C0%7C638100839536069055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FlVy1p9kvZqjIwypPXupCv%2BHSO%2F8%2BRZquKYftKIHrwc%3D&reserved=0>

**Comment by huglester** [comment]
> Hi!, I installed Home-Bridge on a mac to see if that runs and it seems to work, there are 32 connections loaded in Homebridge and they show up in homekit. Only thing is that nothing happens when I try to switch.. And whats even worse, my eNet server crashes. I hope I can get it up and running again… Met vriendelijke groet, Mark Vork Van

so you wanna say, fresh install kinda fixed that "message" error?

**Comment by shanse01** [comment]
Hi!
Kind of the same here (server crashed), runs once with all device showing up but states do not update. On restarting Homebridge all device are gone, uninstall and reinstallation of the plugin does not lead anywhere, no devices at all.

Log:
Loading logs using native method...
File: /var/lib/homebridge/homebridge.log

[1/27/2023, 4:25:48 PM] [Homebridge UI] Running Command: npm install --save homebridge-enet@1.2.0
[1/27/2023, 4:27:28 PM] Loaded plugin: homebridge-enet@1.2.0
[1/27/2023, 4:27:28 PM] Registering platform 'homebridge-enet.eNetPlatform'
[1/27/2023, 4:27:34 PM] [eNetPlatform] Initializing eNetPlatform platform...
[1/27/2023, 4:27:34 PM] [eNetPlatform] eNet start initializing!
[1/27/2023, 4:27:34 PM] Loading 1 accessories... #not sure if this even is related to eNet as there are no device showing up at all

Best regards
Sven

**Comment by huglester** [comment]
Hello

my 'message' error is somehow linked to this fix I was trying to provide maybe?
https://github.com/huglester/homebridge-enet/commit/f6f8eff8979747d3c2d78d818670ae56138bd202#diff-1f1bdaf1cbba9a2540bcd327bec8dca460f736cf33f616334a0311429fdb2ad5R90

**Comment by huglester** [comment]
Hey

anyone managed to start this enet server? 
I really miss this thing :) 

@lawrencebensaid can you take a look? 
https://github.com/lawrencebensaid/homebridge-enet/issues/4

**Comment by huglester** [comment]
@shanse01 maybe you got luck starting it?

**Comment by shanse01** [comment]
@huglesterOnly half way and weirdly enough only once I login to the eNet Server while the process is running on Homebrige. It reads in all appliance but crashes with another error message.UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Unable to fetch devices at this time!".I have tried a lot of things and sent all information I could gather to Lawrence hoping that this might shed some light on where the process fails.Mit freundlichem Gruß/Best regardsSven ***@***.*** 18.02.2023 um 07:33 schrieb huglester ***@***.***>:﻿
@shanse01 maybe you got luck starting it?

**Comment by huglester** [comment]
@lawrencebensaid do you got any time to look further into this?

**Comment by Adversio** [comment]
I moved on to a very complicated work around, involving Home Assistant who can communicate with eNet using Google Home SDK. From there a can at least control my Spa which I only want to heat up when I produce enough solar energy 😊

Met vriendelijke groet,

Mark Vork

**Comment by huglester** [comment]
Hello @Adversio is there a github repo to follow progress and maybe try to learn something?

**Comment by lawrencebensaid** [comment]
Sorry guys, I'm super busy at the moment and don't have the time to do debugging based on these reports. I also don't have the proper equipment accessible right now.
But what I can do is review and merge any PR you guys create.
I hope that helps.

**Comment by shanse01** [comment]
Has anyone upgraded the server to 2.4.0? Apart from our common problem this lead to my eNet-App not being able to switch anything. The status of all objects gets updated when I switch thru a hardware switch immediately though. Service call is open, the technician suggested that this might be linked to my project being encrypted (quite uncommon, he said). He will send it to the lab to test this scenario and revert asap.
Reds
Sven

**Comment by huglester** [comment]
@Adversio any progress maybe? 

Thanks

**Comment by Adversio** [comment]
I created a new way of automating my most important switches. I activated the Google Home integration in eNet and used the Google SDK integration in Home Assistant to automate some processes (mainly the switching of our spa when we produce enough solar power). You can even import the voice commands in Apple Homekit and that sort of works. Still not brilliant but it works. I would still love to have the eNet integration in HomeBridge or Home Assistant.
